import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/navigation/Navigation';
import { LinkModel } from '@/models/navigation/types';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const LINKS1: LinkModel = [
        { name: 'Home', url: '/' },
        { name: 'About', url: '/about' },
        { name: 'Sajt', url: '/sajt' },
    ];
    const LINKS2: LinkModel = [
        { name: 'asd', url: '/' },
        { name: 'dsa', url: '/about' },
        { name: 'aaaaa', url: '/sajt' },
    ];
    return (
        <html lang='en'>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
                <Navigation links={LINKS1} />
                {children}
            </body>
        </html>
    );
}
